server {
    server_name new.simona-bt.ru;
    listen 5.188.30.184:80;
    listen [2a01:5a60:5::5a]:80;
    return 301 https://$host$request_uri;
}

server {
    server_name new.simona-bt.ru;
    listen 5.188.30.184:443 ssl http2;
    listen [2a01:5a60:5::5a]:443 ssl http2;

    ssl_certificate "/var/www/httpd-cert/new.simona-bt.ru_2025-07-20-17-38_03.crt";
    ssl_certificate_key "/var/www/httpd-cert/new.simona-bt.ru_2025-07-20-17-38_03.key";
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    charset utf-8;

    gzip on;
    gzip_proxied any;
    gzip_types text/css text/xml application/javascript text/plain application/json image/svg+xml image/x-icon;
    gzip_comp_level 5;

    # SEO protection: do not index staging
    add_header X-Robots-Tag "noindex, nofollow" always;

    location / {
        proxy_pass http://127.0.0.1:3005;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 120s;
        proxy_connect_timeout 60s;
    }

    error_log /var/www/simona-bt.ru/data/logs/new.simona-bt.ru-frontend.error.log;
    access_log /var/www/simona-bt.ru/data/logs/new.simona-bt.ru-frontend.access.log;
}

server {
    server_name www.new.simona-bt.ru;
    listen 5.188.30.184:80;
    listen [2a01:5a60:5::5a]:80;
    listen 5.188.30.184:443 ssl http2;
    listen [2a01:5a60:5::5a]:443 ssl http2;

    ssl_certificate "/var/www/httpd-cert/new.simona-bt.ru_2025-07-20-17-38_03.crt";
    ssl_certificate_key "/var/www/httpd-cert/new.simona-bt.ru_2025-07-20-17-38_03.key";
    return 301 https://new.simona-bt.ru$request_uri;

    error_log /var/www/simona-bt.ru/data/logs/new.simona-bt.ru-frontend.error.log;
    access_log /var/www/simona-bt.ru/data/logs/new.simona-bt.ru-frontend.access.log;
}
